const $ = (s) => document.querySelector(s), DAY = 86400;
const state = { library: null, programming: null, schedule: [], player: null, current: null, currentKey: '', failed: new Set(), soundWanted: localStorage.getItem('hachijo-tv-sound') === 'on', soundOn: false, ready: false };
function tokyo(date = new Date()) { return Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).formatToParts(date).filter(x => x.type !== 'literal').map(x => [x.type, x.value])); }
function testParts() { const q = new URLSearchParams(location.search), p = tokyo(); if (q.get('date')) [p.year, p.month, p.day] = q.get('date').split('-'); if (q.get('time')) [p.hour, p.minute, p.second = '00'] = q.get('time').split(':'); return p; }
function dayKey(p = testParts()) { return `${p.year}-${p.month}-${p.day}`; }
function seconds(p = testParts()) { return +p.hour * 3600 + +p.minute * 60 + +p.second; }
function formatTime(value) { value = ((Math.round(value / 60) * 60) % DAY + DAY) % DAY; return `${String(Math.floor(value / 3600)).padStart(2, '0')}:${String(Math.floor(value % 3600 / 60)).padStart(2, '0')}`; }
function clock() { const p = testParts(); return `${p.hour}:${p.minute}`; }
function hash(value) { let h = 2166136261; for (const char of value) h = Math.imul(h ^ char.charCodeAt(0), 16777619); return h >>> 0; }
function pick(items, seed) { return items[hash(seed) % items.length]; }
function solar(date, latitude, longitude, rising) { const start = Date.UTC(+date.year, +date.month - 1, +date.day), n = Math.floor((start - Date.UTC(+date.year, 0, 0)) / 86400000), lng = longitude / 15, t = n + ((rising ? 6 : 18) - lng) / 24, m = .9856 * t - 3.289, l = ((m + 1.916 * Math.sin(m * Math.PI / 180) + .020 * Math.sin(2 * m * Math.PI / 180) + 282.634) % 360 + 360) % 360, ra0 = Math.atan(.91764 * Math.tan(l * Math.PI / 180)) * 180 / Math.PI, ra = ((ra0 + (Math.floor(l / 90) * 90 - Math.floor(ra0 / 90) * 90)) % 360 + 360) % 360 / 15, sinDec = .39782 * Math.sin(l * Math.PI / 180), cosDec = Math.cos(Math.asin(sinDec)), cosH = (Math.cos(90.833 * Math.PI / 180) - sinDec * Math.sin(latitude * Math.PI / 180)) / (cosDec * Math.cos(latitude * Math.PI / 180)); if (Math.abs(cosH) > 1) return rising ? 6 * 3600 : 18 * 3600; const h = (rising ? 360 - Math.acos(cosH) * 180 / Math.PI : Math.acos(cosH) * 180 / Math.PI) / 15, ut = h + ra - .06571 * t - 6.622 - lng; return Math.round((((ut + 9) % 24 + 24) % 24) * 3600); }
function source(id) { return { ...state.library.sources[id] }; }
function segment(start, duration, src, overrides = {}) { return { start: Math.max(0, Math.round(start)), end: Math.min(DAY, Math.round(start + duration)), ...src, ...overrides }; }
function taikoSlot(start, slotName, key, used) { const pool = state.library.taikoArchivePool, first = pick(pool, `${key}:${slotName}`), item = used.has(first.id) ? pool[(pool.indexOf(first) + 1 + hash(`${key}:alternate`) % (pool.length - 1)) % pool.length] : first; used.add(item.id); const usable = item.duration - state.programming.anchors.taiko.duration - 60, offset = 60 + (hash(`${key}:${slotName}:offset`) % usable); return segment(start, state.programming.anchors.taiko.duration, item, { type: 'vod', programLabel: 'HACHIJO TAIKO', detail: 'ARCHIVE SELECTION', sourceOffset: offset, archiveYear: item.archiveYear, debug: { source: item.id, offset } }); }
function fill(start, end, key) { const output = []; let cursor = start, i = 0; while (cursor < end) { const hour = Math.floor(cursor / 3600), remaining = end - cursor, night = hour >= 20 || hour < 5, available = night ? remaining : Math.min(remaining, 20 * 3600 - cursor); let id = night ? pick(['jazz-scene', 'city-lights', 'after-hours'], `${key}:music:${i}`) : pick(['sokodo', 'yaene', 'taiko-archive', 'taiko-short'], `${key}:day:${i}`); let src = source(id); if (night && available < src.duration) { id = 'sokodo'; src = source(id); } const size = src.type === 'vod' ? Math.min(src.duration, available) : Math.min(3600, available); const programLabel = hour < 5 || hour >= 23 ? 'AFTER HOURS' : (hour < 20 || id === 'sokodo' ? 'ISLAND WINDOW' : src.programLabel); output.push(segment(cursor, size, src, { programLabel })); cursor += size; i++; } return output; }
function buildSchedule(date = testParts()) { const p = state.programming, key = `${date.year}-${date.month}-${date.day}`, sunrise = solar(date, p.location.latitude, p.location.longitude, true), sunset = solar(date, p.location.latitude, p.location.longitude, false), used = new Set(); const dayTaiko = 11 * 3600 + (hash(`${key}:day-time`) % 54) * 300, nightTaiko = 20 * 3600 + (hash(`${key}:night-time`) % 18) * 300; const anchors = [segment(sunrise - p.solar.dawnBefore, p.solar.dawnBefore + p.solar.dawnAfter, source('sokodo'), { programLabel: 'DAWN', detail: `SOKODO / HACHIJOJIMA · SUNRISE ${formatTime(sunrise)}` }), segment(sunset - p.solar.sunsetBefore, p.solar.sunsetBefore + p.solar.sunsetAfter, source('yaene'), { programLabel: 'SUNSET', detail: `YAENE / HACHIJOJIMA · SUNSET ${formatTime(sunset)}` }), segment(p.anchors.tokyoRelay.start, p.anchors.tokyoRelay.duration, source('tokyo-relay')), taikoSlot(dayTaiko, 'day', key, used), taikoSlot(nightTaiko, 'night', key, used)].sort((a, b) => a.start - b.start); const selected = []; for (const item of anchors) { const prior = selected.at(-1); if (!prior || item.start >= prior.end) selected.push(item); } let cursor = 0, all = []; for (const item of selected) { all = all.concat(fill(cursor, item.start, key)); all.push(item); cursor = item.end; } return all.concat(fill(cursor, DAY, key)); }
function atNow() { const now = seconds(), index = state.schedule.findIndex(x => now >= x.start && now < x.end); if (index < 0) return null; return { item: state.schedule[index], elapsed: now - state.schedule[index].start, next: state.schedule[index + 1] || state.schedule[0], nextAt: state.schedule[index + 1]?.start ?? DAY }; }
function message(value) { const el = $('#player-message'); el.textContent = value; el.hidden = !value; }
function text(program) { if (!program) return; const { item, next, nextAt } = program; $('#on-air-label').textContent = item.programLabel === 'LIVE' ? 'LIVE' : 'NOW'; $('#now-title').textContent = item.programLabel; $('#now-channel').textContent = item.detail || item.sourceChannel || ''; $('#now-meta').textContent = item.programLabel === 'DAWN' || item.programLabel === 'SUNSET' ? item.programLabel : ''; $('#next-label').textContent = `NEXT ${formatTime(nextAt)}`; $('#next-title').textContent = next.programLabel; }
function renderToday() { const blocks = state.schedule.filter((item, index, all) => !index || item.programLabel !== all[index - 1].programLabel); $('#today-list').innerHTML = blocks.map(item => `<p><time>${formatTime(item.start)}</time><span>${item.programLabel}</span></p>`).join(''); }
function soundLabel() { const b = $('#sound-toggle'), on = state.soundOn; b.querySelector('.sound-text').textContent = on ? '音を消す' : '音を出す'; b.setAttribute('aria-label', on ? '音を消す' : '音を出す'); b.setAttribute('aria-pressed', String(on)); }
function sync(force = false) { const program = atNow(); text(program); if (!program || !state.ready) return; const key = `${dayKey()}:${program.item.start}:${program.item.youtubeId}`; if (!force && key === state.currentKey) return; state.current = program; state.currentKey = key; state.player.mute(); state.soundOn = false; state.player.loadVideoById({ videoId: program.item.youtubeId, startSeconds: program.item.type === 'vod' ? Math.floor((program.item.sourceOffset || 0) + program.elapsed) : 0 }); state.player.playVideo(); soundLabel(); if (state.soundWanted) setTimeout(() => { state.player.unMute(); state.player.playVideo(); setTimeout(() => { state.soundOn = !state.player.isMuted(); state.soundWanted = state.soundOn; localStorage.setItem('hachijo-tv-sound', state.soundOn ? 'on' : 'off'); soundLabel(); }, 300); }, 450); message(''); }
function skipError() { if (!state.current) return; state.failed.add(state.current.item.youtubeId); state.currentKey = ''; sync(true); }
window.onYouTubeIframeAPIReady = () => { state.player = new YT.Player('player', { width: '100%', height: '100%', playerVars: { autoplay: 1, controls: 1, playsinline: 1, rel: 0, origin: location.origin }, events: { onReady: () => { state.ready = true; sync(true); }, onError: skipError, onAutoplayBlocked: () => { state.player.mute(); state.player.playVideo(); } } }); };
async function start() { $('#clock').textContent = clock(); soundLabel(); setInterval(() => $('#clock').textContent = clock(), 1000); try { const [library, programming] = await Promise.all(['library.json', 'programming.json'].map(url => fetch(url, { cache: 'no-store' }).then(r => r.ok ? r.json() : Promise.reject()))); state.library = library; state.programming = programming; state.schedule = buildSchedule(); renderToday(); text(atNow()); console.info('FM八丈島 TV schedule', { date: dayKey(), schedule: state.schedule.filter(x => x.debug).map(x => ({ label: x.programLabel, start: formatTime(x.start), ...x.debug })) }); } catch { message('編成を読み込めませんでした。'); } $('#sound-toggle').addEventListener('click', () => { const turnOn = !state.soundOn; state.soundWanted = turnOn; localStorage.setItem('hachijo-tv-sound', turnOn ? 'on' : 'off'); if (!state.player) return; if (!turnOn) { state.player.mute(); state.soundOn = false; return soundLabel(); } state.player.unMute(); state.player.playVideo(); setTimeout(() => { state.soundOn = !state.player.isMuted(); state.soundWanted = state.soundOn; localStorage.setItem('hachijo-tv-sound', state.soundOn ? 'on' : 'off'); soundLabel(); }, 100); }); $('#today-toggle').addEventListener('click', () => { const list = $('#today-list'), open = list.hidden; list.hidden = !open; $('#today-toggle').setAttribute('aria-expanded', String(open)); $('#today-toggle').textContent = open ? 'CLOSE TODAY' : 'VIEW TODAY'; }); document.addEventListener('visibilitychange', () => { if (!document.hidden) { state.schedule = buildSchedule(); renderToday(); sync(true); } }); setInterval(() => sync(), 5000); }
start();
