const $ = s => document.querySelector(s), DAY = 86400;
const state = { library: null, programming: null, schedule: [], player: null, current: null, currentKey: '', failed: new Set(), forced: null, soundWanted: localStorage.getItem('hachijo-tv-sound') === 'on', soundOn: false, ready: false };
const taikoPlanCache = new Map();

function tokyo(date = new Date()) { return Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).formatToParts(date).filter(x => x.type !== 'literal').map(x => [x.type, x.value])); }
function testParts() { const q = new URLSearchParams(location.search), p = tokyo(); if (q.get('date')) [p.year, p.month, p.day] = q.get('date').split('-'); if (q.get('time')) [p.hour, p.minute, p.second = '00'] = q.get('time').split(':'); return p; }
function dayKey(p = testParts()) { return `${p.year}-${p.month}-${p.day}`; }
function seconds(p = testParts()) { return +p.hour * 3600 + +p.minute * 60 + +p.second; }
function formatTime(value) { value = ((Math.round(value / 60) * 60) % DAY + DAY) % DAY; return `${String(Math.floor(value / 3600)).padStart(2, '0')}:${String(Math.floor(value % 3600 / 60)).padStart(2, '0')}`; }
function clock() { const p = testParts(); return `${p.hour}:${p.minute}`; }
function hash(value) { let h = 2166136261; for (const char of value) h = Math.imul(h ^ char.charCodeAt(0), 16777619); return h >>> 0; }
function pick(items, seed) { return items[hash(seed) % items.length]; }
function shiftDate(date, delta) { const d = new Date(Date.UTC(+date.year, +date.month - 1, +date.day + delta)); return { year: String(d.getUTCFullYear()), month: String(d.getUTCMonth() + 1).padStart(2, '0'), day: String(d.getUTCDate()).padStart(2, '0') }; }
function solar(date, latitude, longitude, rising) { const start = Date.UTC(+date.year, +date.month - 1, +date.day), n = Math.floor((start - Date.UTC(+date.year, 0, 0)) / 86400000), lng = longitude / 15, t = n + ((rising ? 6 : 18) - lng) / 24, m = .9856 * t - 3.289, l = ((m + 1.916 * Math.sin(m * Math.PI / 180) + .020 * Math.sin(2 * m * Math.PI / 180) + 282.634) % 360 + 360) % 360, ra0 = Math.atan(.91764 * Math.tan(l * Math.PI / 180)) * 180 / Math.PI, ra = ((ra0 + (Math.floor(l / 90) * 90 - Math.floor(ra0 / 90) * 90)) % 360 + 360) % 360 / 15, sinDec = .39782 * Math.sin(l * Math.PI / 180), cosDec = Math.cos(Math.asin(sinDec)), cosH = (Math.cos(90.833 * Math.PI / 180) - sinDec * Math.sin(latitude * Math.PI / 180)) / (cosDec * Math.cos(latitude * Math.PI / 180)); if (Math.abs(cosH) > 1) return rising ? 21600 : 64800; const h = (rising ? 360 - Math.acos(cosH) * 180 / Math.PI : Math.acos(cosH) * 180 / Math.PI) / 15, ut = h + ra - .06571 * t - 6.622 - lng; return Math.round((((ut + 9) % 24 + 24) % 24) * 3600); }
function source(id) { return { ...state.library.sources[id] }; }
function segment(start, duration, src, overrides = {}) { return { start: Math.max(0, Math.round(start)), end: Math.min(DAY, Math.round(start + duration)), ...src, ...overrides }; }
function overlaps(a, b) { return a.start < b.end && a.end > b.start; }
function daypartAt(second) { return state.programming.dayparts.find(part => second >= part.start && second < part.end) || state.programming.dayparts[0]; }

function taikoMetrics() { const pool = state.library.archivePools.hachijoTaiko, segmentDuration = pool.segmentDuration, usableBlockCount = pool.sources.reduce((sum, item) => sum + Math.floor(item.duration / segmentDuration), 0), theoreticalCycleDays = Math.floor(usableBlockCount / state.programming.pools.hachijoTaiko.slots.length), hardCooldownDays = Math.max(1, theoreticalCycleDays - state.programming.taikoCooldown.safetyDays); return { totalDuration: pool.sources.reduce((sum, item) => sum + item.duration, 0), usableBlockCount, theoreticalCycleDays, hardCooldownDays }; }
function compareDate(a, b) { return a.year.localeCompare(b.year) || a.month.localeCompare(b.month) || a.day.localeCompare(b.day); }
function taikoCandidateBlocks() { const pool = state.library.archivePools.hachijoTaiko, duration = pool.segmentDuration; return pool.sources.flatMap(item => Array.from({ length: Math.floor(item.duration / duration) }, (_, block) => ({ item, offset: block * duration, end: (block + 1) * duration }))); }
function intervalsOverlap(a, b) { return a.offset < b.end && a.end > b.offset; }
function taikoPlan(date) {
  const key = dayKey(date); if (taikoPlanCache.has(key)) return taikoPlanCache.get(key);
  const seed = state.programming.taikoCooldown.seedDate.split('-'), cursor = { year: seed[0], month: seed[1], day: seed[2] }, slots = state.programming.pools.hachijoTaiko.slots, metrics = taikoMetrics(), blocks = taikoCandidateBlocks();
  while (compareDate(cursor, date) <= 0) { const cursorKey = dayKey(cursor); if (!taikoPlanCache.has(cursorKey)) { const plan = []; for (const slot of slots) { let selected = null, cooldownDaysUsed = metrics.hardCooldownDays; for (; cooldownDaysUsed >= 0 && !selected; cooldownDaysUsed--) { const recent = []; for (let day = 1; day <= cooldownDaysUsed; day++) recent.push(...(taikoPlanCache.get(dayKey(shiftDate(cursor, -day))) || [])); const ordered = blocks.slice().sort((a, b) => hash(`${cursorKey}:${slot.name}:${a.item.id}:${a.offset}`) - hash(`${cursorKey}:${slot.name}:${b.item.id}:${b.offset}`)); selected = ordered.find(candidate => !plan.some(previous => previous.item.id === candidate.item.id) && !recent.some(previous => previous.item.id === candidate.item.id && intervalsOverlap(candidate, previous))); } if (!selected) selected = blocks.slice().sort((a, b) => hash(`${cursorKey}:${slot.name}:${a.item.id}:${a.offset}`) - hash(`${cursorKey}:${slot.name}:${b.item.id}:${b.offset}`))[0]; plan.push({ ...selected, slotName: slot.name, cooldownDaysUsed: Math.max(0, cooldownDaysUsed + 1) }); } taikoPlanCache.set(cursorKey, plan); } Object.assign(cursor, shiftDate(cursor, 1)); }
  return taikoPlanCache.get(key);
}

function poolChoice(poolId, date, slotName, duration, used) {
  const pool = state.library.archivePools[poolId], key = dayKey(date), history = [];
  for (let day = 1; day <= 50; day++) for (const slot of used.slotNames) history.push(poolBase(pool, shiftDate(date, -day), slot, duration));
  const ranked = pool.sources.map((item, index) => {
    const room = item.duration - duration - 120, offset = 60 + hash(`${key}:${poolId}:${slotName}:${item.id}:offset`) % room;
    let penalty = used.ids.has(item.id) ? 10000000 : 0;
    for (const previous of history) if (previous.item.id === item.id) penalty += Math.max(0, 5400 - Math.abs(offset - previous.offset));
    return { item, offset, penalty, index };
  }).sort((a, b) => a.penalty - b.penalty || a.index - b.index)[0];
  used.ids.add(ranked.item.id);
  return ranked;
}
function poolBase(pool, date, slotName, duration) { const item = pick(pool.sources, `${dayKey(date)}:${pool.programLabel}:${slotName}:source`), room = item.duration - duration - 120; return { item, offset: 60 + hash(`${dayKey(date)}:${pool.programLabel}:${slotName}:offset`) % room }; }
function poolSegment(poolId, start, date, slotName, duration, used) {
  const pool = state.library.archivePools[poolId], chosen = poolId === 'hachijoTaiko' ? taikoPlan(date).find(item => item.slotName === slotName) : poolChoice(poolId, date, slotName, duration, used);
  return segment(start, duration, chosen.item, { type: 'vod', programLabel: pool.programLabel, detail: 'ARCHIVE SELECTION', sourceOffset: chosen.offset, archiveYear: chosen.item.archiveYear, debug: { pool: poolId, source: chosen.item.id, offset: chosen.offset, ...(poolId === 'hachijoTaiko' ? taikoMetrics() : {}) } });
}
function chooseStart(candidates, duration, occupied, seed, label = '') { const ordered = candidates.map((start, index) => ({ start, index })).sort((a, b) => (hash(`${seed}:${a.start}`) - hash(`${seed}:${b.start}`)) || a.index - b.index); return ordered.map(x => x.start).find(start => !occupied.some(item => overlaps({ start, end: start + duration }, item) || (label && item.programLabel === label && Math.min(Math.abs(start - item.end), Math.abs(item.start - (start + duration))) < 600))); }
function eventAnchors(date) { return state.programming.events.filter(event => event.start.slice(0, 10) === dayKey(date)).map(event => { const [, time] = event.start.split('T'), [hour, minute] = time.split(':').map(Number), start = hour * 3600 + minute * 60; return segment(start, (new Date(event.end) - new Date(event.start)) / 1000, { type: 'live', youtubeId: event.youtubeId, sourceChannel: event.sourceChannel || '' }, { programLabel: 'LIVE', detail: event.detail || 'EVENT LIVE' }); }); }
function hardAnchors(date) {
  const p = state.programming, sunrise = solar(date, p.location.latitude, p.location.longitude, true), sunset = solar(date, p.location.latitude, p.location.longitude, false), events = eventAnchors(date), regular = [
    segment(sunrise - p.solar.dawnBefore, p.solar.dawnBefore + p.solar.dawnAfter, source('sokodo'), { programLabel: 'DAWN', detail: `SOKODO / HACHIJOJIMA · SUNRISE ${formatTime(sunrise)}` }),
    segment(sunset - p.solar.sunsetBefore, p.solar.sunsetBefore + p.solar.sunsetAfter, source('yaene'), { programLabel: 'SUNSET', detail: `YAENE / HACHIJOJIMA · SUNSET ${formatTime(sunset)}` }),
    segment(p.anchors.tokyoRelay.start, p.anchors.tokyoRelay.duration, source('tokyo-relay'))
  ];
  return events.concat(regular.filter(item => !events.some(event => overlaps(item, event)))).sort((a, b) => a.start - b.start);
}
function scheduledPools(date, occupied) {
  const p = state.programming, output = [], taikoUsed = { ids: new Set(), slotNames: p.pools.hachijoTaiko.slots.map(slot => slot.name) };
  for (const slot of p.pools.hachijoTaiko.slots) { const start = chooseStart(slot.candidates, state.library.archivePools.hachijoTaiko.segmentDuration, occupied.concat(output), `${dayKey(date)}:taiko:${slot.name}`, 'HACHIJO TAIKO'); if (start !== undefined) output.push(poolSegment('hachijoTaiko', start, date, slot.name, state.library.archivePools.hachijoTaiko.segmentDuration, taikoUsed)); }
  const count = hash(`${dayKey(date)}:island-league:count`) % (p.pools.islandLeague.maxDailySlots + 1), leagueUsed = { ids: new Set(), slotNames: ['first', 'second'] };
  for (let index = 0; index < count; index++) { const pool = state.library.archivePools.islandLeague, span = pool.segmentMin + hash(`${dayKey(date)}:league:${index}:duration`) % (pool.segmentMax - pool.segmentMin + 1), start = chooseStart(p.pools.islandLeague.candidates, span, occupied.concat(output), `${dayKey(date)}:league:${index}`); if (start !== undefined) output.push(poolSegment('islandLeague', start, date, index ? 'second' : 'first', span, leagueUsed)); }
  return output.sort((a, b) => a.start - b.start);
}
function chooseArchive(available, key, index, used) { const catalog = state.library.catalogs.islandArchive, fitting = ids => ids.filter(id => source(id).duration <= available), fresh = fitting(catalog.filter(id => !used.has(id))), reusable = fitting(catalog); let id = fresh.length ? pick(fresh, `${key}:archive:${index}`) : reusable.length ? pick(reusable, `${key}:archive:repeat:${index}`) : null; if (id) { used.add(id); return source(id); } const partial = catalog.filter(id => !source(id).atomic && source(id).duration > available); if (!partial.length) return null; id = pick(partial, `${key}:archive:partial:${index}`); const src = source(id), maxOffset = Math.max(0, src.duration - available); used.add(id); return { ...src, playDuration: available, sourceOffset: maxOffset ? hash(`${key}:${index}:${id}:offset`) % (maxOffset + 1) : 0, detail: 'ISLAND PROGRAMMING' }; }
function chooseMusic(available, key, index, used) { const families = state.library.catalogs.nightMusic, usable = label => families[label].filter(id => source(id).duration <= available), fresh = Object.keys(families).filter(label => usable(label).some(id => !used.has(id))); const labels = fresh.length ? fresh : Object.keys(families).filter(label => usable(label).length); if (!labels.length) return null; const label = pick(labels, `${key}:family:${index}`), ids = fresh.length ? usable(label).filter(id => !used.has(id)) : usable(label), id = pick(ids, `${key}:music:${index}`); used.add(id); return { ...source(id), programLabel: label }; }
function fallbackCamera(start, duration, key) { const id = pick(state.library.catalogs.cameraFallback, `${key}:camera:${start}`); return segment(start, duration, source(id), { programLabel: 'ISLAND CAMERA', detail: 'ISLAND WINDOW' }); }
function fillGap(start, end, date, used) { const output = [], key = dayKey(date); let cursor = start, index = Math.floor(start / 60); while (cursor < end) { const part = daypartAt(cursor), available = end - cursor, music = part.family === 'nightMusic'; let src = music ? chooseMusic(available, key, index, used.music) : chooseArchive(available, key, index, used.archive); if (!src && music) src = chooseArchive(available, key, index, used.archive); if (src) { const duration = src.playDuration || src.duration; output.push(segment(cursor, duration, src)); cursor += duration; } else { const duration = Math.min(available, state.programming.cameraFallback.maxBlock); output.push(fallbackCamera(cursor, duration, key)); cursor += duration; } index++; } return output; }
function fillWithClockAnchors(start, end, date, used) { const points = state.programming.anchors.clock.filter(point => point > start && point < end).concat(end); let cursor = start, output = []; for (const point of points) { output.push(...fillGap(cursor, point, date, used)); cursor = point; } return output; }
function buildSchedule(date = testParts()) { const hard = hardAnchors(date), protectedBlocks = scheduledPools(date, hard), anchors = hard.concat(protectedBlocks).sort((a, b) => a.start - b.start), used = { archive: new Set(), music: new Set() }, output = []; let cursor = 0; for (const item of anchors) { if (item.start < cursor) continue; output.push(...fillWithClockAnchors(cursor, item.start, date, used), item); cursor = item.end; } return output.concat(fillWithClockAnchors(cursor, DAY, date, used)).sort((a, b) => a.start - b.start); }

function atNow() { const now = seconds(), index = state.schedule.findIndex(x => now >= x.start && now < x.end); if (index < 0) return null; const scheduled = state.schedule[index]; if (!state.failed.has(scheduled.youtubeId)) state.forced = null; if (state.forced) return state.forced; return { item: scheduled, elapsed: now - scheduled.start, next: state.schedule[index + 1] || state.schedule[0], nextAt: state.schedule[index + 1]?.start ?? DAY }; }
function message(value) { const el = $('#player-message'); el.textContent = value; el.hidden = !value; }
function text(program) { if (!program) return; const { item, next, nextAt } = program; $('#on-air-label').textContent = item.programLabel === 'LIVE' ? 'LIVE' : 'NOW'; $('#now-title').textContent = item.programLabel; $('#now-channel').textContent = item.sourceChannel || item.detail || ''; $('#now-meta').textContent = item.programLabel === 'DAWN' || item.programLabel === 'SUNSET' ? item.programLabel : ''; $('#next-label').textContent = `NEXT ${formatTime(nextAt)}`; $('#next-title').textContent = next.programLabel; }
function renderToday() { const clockAnchors = new Set(state.programming.anchors.clock); const blocks = state.schedule.filter((item, index, all) => !index || item.debug || item.programLabel !== all[index - 1].programLabel || clockAnchors.has(item.start)); $('#today-list').innerHTML = blocks.map(item => `<p><time>${formatTime(item.start)}</time><span>${item.programLabel}</span></p>`).join(''); }
function soundLabel() { const b = $('#sound-toggle'), on = state.soundOn; b.querySelector('.sound-text').textContent = on ? '音を消す' : '音を出す'; b.setAttribute('aria-label', on ? '音を消す' : '音を出す'); b.setAttribute('aria-pressed', String(on)); }
function sync(force = false) { const program = atNow(); text(program); if (!program || !state.ready) return; const key = `${dayKey()}:${program.item.start}:${program.item.youtubeId}`; if (!force && key === state.currentKey) return; state.current = program; state.currentKey = key; state.player.mute(); state.soundOn = false; state.player.loadVideoById({ videoId: program.item.youtubeId, startSeconds: program.item.type === 'vod' ? Math.floor((program.item.sourceOffset || 0) + program.elapsed) : 0 }); state.player.playVideo(); soundLabel(); if (state.soundWanted) setTimeout(() => { state.player.unMute(); state.player.playVideo(); setTimeout(() => { state.soundOn = !state.player.isMuted(); state.soundWanted = state.soundOn; localStorage.setItem('hachijo-tv-sound', state.soundOn ? 'on' : 'off'); soundLabel(); }, 300); }, 450); message(''); }
function skipError() { if (!state.current) return; state.failed.add(state.current.item.youtubeId); const unique = [...new Set(state.schedule.map(item => item.youtubeId))]; if (unique.every(id => state.failed.has(id))) { message('現在利用できる映像がありません。'); return; } const index = state.schedule.findIndex(item => item === state.current.item), nextIndex = state.schedule.findIndex((item, i) => i > index && !state.failed.has(item.youtubeId)), fallbackIndex = nextIndex >= 0 ? nextIndex : state.schedule.findIndex(item => !state.failed.has(item.youtubeId)), item = state.schedule[fallbackIndex], next = state.schedule[fallbackIndex + 1] || state.schedule[0]; state.forced = { item, elapsed: 0, next, nextAt: item.start }; state.currentKey = ''; sync(true); }
window.onYouTubeIframeAPIReady = () => { state.player = new YT.Player('player', { width: '100%', height: '100%', playerVars: { autoplay: 1, controls: 0, playsinline: 1, rel: 0, origin: location.origin }, events: { onReady: () => { state.ready = true; sync(true); }, onError: skipError, onAutoplayBlocked: () => { state.player.mute(); state.player.playVideo(); } } }); };
async function start() { $('#clock').textContent = clock(); soundLabel(); setInterval(() => $('#clock').textContent = clock(), 1000); try { const [library, programming] = await Promise.all(['library.json', 'programming.json'].map(url => fetch(url, { cache: 'no-store' }).then(r => r.ok ? r.json() : Promise.reject()))); state.library = library; state.programming = programming; state.schedule = buildSchedule(); renderToday(); text(atNow()); console.info('FM八丈島 TV schedule', { date: dayKey(), taikoMetrics: taikoMetrics(), pools: state.schedule.filter(x => x.debug).map(x => ({ label: x.programLabel, start: formatTime(x.start), end: formatTime(x.end), ...x.debug })) }); } catch { message('編成を読み込めませんでした。'); } $('#sound-toggle').addEventListener('click', () => { const turnOn = !state.soundOn; state.soundWanted = turnOn; localStorage.setItem('hachijo-tv-sound', turnOn ? 'on' : 'off'); if (!state.player) return; if (!turnOn) { state.player.mute(); state.soundOn = false; return soundLabel(); } state.player.unMute(); state.player.playVideo(); setTimeout(() => { state.soundOn = !state.player.isMuted(); state.soundWanted = state.soundOn; localStorage.setItem('hachijo-tv-sound', state.soundOn ? 'on' : 'off'); soundLabel(); }, 100); }); $('#today-toggle').addEventListener('click', () => { const list = $('#today-list'), open = list.hidden; list.hidden = !open; $('#today-toggle').setAttribute('aria-expanded', String(open)); $('#today-toggle').textContent = open ? 'CLOSE TODAY' : 'VIEW TODAY'; }); document.addEventListener('visibilitychange', () => { if (!document.hidden) { state.schedule = buildSchedule(); renderToday(); sync(); } }); setInterval(() => sync(), 5000); }
start();
