const $ = selector => document.querySelector(selector);
const sb = window.supabase.createClient(window.FM_HACHIJO_SUPABASE.url, window.FM_HACHIJO_SUPABASE.publishableKey);
const state = { player: null, current: null, key: '', boundaryTimer: null, soundOn: false, soundWanted: localStorage.getItem('hachijo-tv-sound') === 'on', initialising: false };
const familyName = { music: 'MUSIC', hachijo_taiko: 'HACHIJO TAIKO', power_push: 'POWER PLAY', sports: 'SPORTS', hachijo_picks: 'HACHIJO PICKS', island_view: 'ISLAND VIEW', tokyo_relay: 'TOKYO RELAY' };
const formatTime = value => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(value));
const message = value => { $('#player-message').textContent = value; $('#player-message').hidden = !value; };
function showProgram(prefix, program) { const isDeparture = program?.family_code === 'tokyo_relay' && formatTime(program.start_at) === '22:30' && formatTime(program.end_at) === '22:50'; const showTitle = ['music', 'power_push', 'hachijo_picks', 'island_view'].includes(program?.family_code); const displayTitle = program?.family_code === 'tokyo_relay' ? (isDeparture ? 'DEPARTURE' : '放送休止') : (showTitle ? (program.title || '') : ''); $(`#${prefix}-family`).textContent = program ? familyName[program.family_code] : '—'; $(`#${prefix}-title`).textContent = displayTitle; }
function soundLabel() { const button = $('#sound-toggle'); button.querySelector('span').textContent = state.soundOn ? '音を消す' : '音を出す'; button.setAttribute('aria-label', state.soundOn ? '音を消す' : '音を出す'); button.setAttribute('aria-pressed', String(state.soundOn)); }
const jstDateKey = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
function showAccessTotal(total) { document.querySelector("#presence-count").textContent = `${Number(total || 0)}人`; document.querySelector("#presence-status").setAttribute("aria-label", `${Number(total || 0)}人がみています`); }
async function recordAccess() { try { const key = `fmh_access_recorded_${jstDateKey()}`; if (sessionStorage.getItem(key)) { const { data, error } = await sb.rpc("access_total"); if (!error) showAccessTotal(data); return; } const { data, error } = await sb.rpc("record_access"); if (error) return; sessionStorage.setItem(key, '1'); showAccessTotal(data); } catch {} }
const hot10Weekdays = ['Sun.', 'Mon.', 'Tue.', 'Wed.', 'Thu.', 'Fri.', 'Sat.'];
function hot10MovementLabel(movement) { if (movement === 'NEW') return 'NEW'; if (movement === 'RE') return 'RE'; if (movement === '→') return '順位変動なし'; const match = /^([↑↓])(\d+)$/.exec(movement || ''); return match ? `${match[2]}位${match[1] === '↑' ? '上昇' : '下降'}` : (movement || '順位情報なし'); }
function renderHot10Date(date) { const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(date || ''); if (!match) throw new Error('Invalid HOT10 date'); const [year, month, day] = match.slice(1); const weekday = hot10Weekdays[new Date(Date.UTC(Number(year), Number(month) - 1, Number(day))).getUTCDay()]; $('#hot10-date').setAttribute('aria-label', `${Number(year)}年${Number(month)}月${Number(day)}日 ${weekday}`); $('.hot10-month-day').textContent = `${Number(month)}.${day}`; $('.hot10-weekday').textContent = weekday; $('.hot10-year').textContent = year; }
function renderHot10(chart) { const list = $('#hot10-list'); list.replaceChildren(); chart.forEach(item => { const row = document.createElement('li'); const movement = item.movement || '—'; const movementClass = movement === 'NEW' ? ' is-new' : movement === 'RE' ? ' is-re' : movement.startsWith('↑') ? ' is-up' : movement.startsWith('↓') ? ' is-down' : movement === '→' ? ' is-flat' : ''; row.className = 'hot10-row'; const rankGroup = document.createElement('span'); rankGroup.className = 'hot10-rank-block'; const rank = document.createElement('span'); rank.className = 'hot10-rank'; rank.textContent = String(item.rank).padStart(2, '0'); const move = document.createElement('span'); move.className = `hot10-movement${movementClass}`; move.textContent = movement; move.setAttribute('aria-label', hot10MovementLabel(movement)); rankGroup.append(rank, move); const title = document.createElement('span'); title.className = 'hot10-title'; title.textContent = item.title || '—'; const artist = document.createElement('span'); artist.className = 'hot10-artist'; artist.textContent = item.artist || '—'; row.append(rankGroup, title, artist); list.append(row); }); }
async function loadHot10() { const section = $('#hachijo-hot10'); try { const url = new URL('hachijo_hot10/hot10_output/latest.json', document.baseURI); url.searchParams.set('v', Date.now().toString()); const response = await fetch(url, { cache: 'no-store' }); if (!response.ok) throw new Error(`HOT10 fetch failed: ${response.status}`); const data = await response.json(); if (!data?.date || !Array.isArray(data.chart) || data.chart.length !== 10) throw new Error('Invalid HOT10 payload'); renderHot10Date(data.date); renderHot10(data.chart); } catch (error) { console.error('Unable to load HACHIJO HOT 10', error); $('#hot10-list').replaceChildren(Object.assign(document.createElement('li'), { className: 'hot10-error', textContent: 'ランキングを読み込めませんでした' })); } finally { section.setAttribute('aria-busy', 'false'); } }
async function readTimeline() { const now = new Date().toISOString(); const { data: current, error } = await sb.from('schedule_items').select('*').lte('start_at', now).gt('end_at', now).order('start_at', { ascending: false }).limit(1).maybeSingle(); if (error) throw error; if (!current) return { current: null, next: null }; const { data: next, error: nextError } = await sb.from('schedule_items').select('*').gte('start_at', current.end_at).order('start_at').limit(1).maybeSingle(); if (nextError) throw nextError; return { current, next }; }
function scheduleBoundary(current) { clearTimeout(state.boundaryTimer); const delay = Math.max(1000, new Date(current.end_at).getTime() - Date.now() + 200); state.boundaryTimer = setTimeout(() => sync(true), delay); }
function startSecondsFor(current) { const elapsed = Math.max(0, Math.floor((Date.now() - new Date(current.start_at).getTime()) / 1000)); return ['island_view', 'tokyo_relay'].includes(current.family_code) ? 0 : (current.start_offset_seconds || 0) + elapsed; }
function restoreSound() { if (state.soundWanted) setTimeout(() => { state.player.unMute(); state.player.playVideo(); setTimeout(() => { state.soundOn = !state.player.isMuted(); soundLabel(); }, 300); }, 350); }
function loadCurrent(current, force = false) { const key = `${current.id}:${current.start_at}`; if (!force && key === state.key) return; state.key = key; state.current = current; state.player.mute(); state.soundOn = false; soundLabel(); state.player.loadVideoById({ videoId: current.youtube_id, startSeconds: startSecondsFor(current) }); state.player.playVideo(); restoreSound(); }
function renderTimeline({ current, next }, force = false) { if (!current) { message('現在の編成を準備中です。'); $('#now-start').textContent = ''; $('#next-start').textContent = ''; showProgram('now', null); showProgram('next', null); return; } message(''); $('#now-start').textContent = ` ${formatTime(current.start_at)}から`; $('#next-start').textContent = next ? ` ${formatTime(next.start_at)}から` : ''; showProgram('now', current); showProgram('next', next); if (state.player) loadCurrent(current, force); scheduleBoundary(current); }
async function sync(force = false) { try { renderTimeline(await readTimeline(), force); } catch { message('編成を読み込めませんでした。'); } }
const isIPhone = () => /iPhone|iPod/.test(navigator.userAgent);
function fullscreenLabel(active) { const button = $('#fullscreen-toggle'); button.querySelector('span').textContent = active ? '全画面を閉じる' : '全画面'; button.setAttribute('aria-label', active ? '全画面を閉じる' : '全画面'); button.setAttribute('aria-pressed', String(active)); }
function unlockOrientation() { globalThis.screen?.orientation?.unlock?.(); }
function fullscreen() { const container = $('.screen'); if (isIPhone()) { const active = container.classList.toggle('ios-immersive'); document.body.classList.toggle('ios-immersive', active); fullscreenLabel(active); if (active) { globalThis.screen?.orientation?.lock?.('landscape')?.catch?.(() => {}); window.scrollTo(0, 0); } else unlockOrientation(); return; } const active = document.fullscreenElement || document.webkitFullscreenElement; if (active) return (document.exitFullscreen || document.webkitExitFullscreen).call(document); const request = container.requestFullscreen || container.webkitRequestFullscreen; return request?.call(container)?.then?.(() => globalThis.screen?.orientation?.lock?.('landscape')).catch?.(() => {}); }
const startupTimeline = readTimeline();
function createInitialPlayer(current) { const key = `${current.id}:${current.start_at}`, startSeconds = startSecondsFor(current), playerVars = { autoplay: 1, controls: 0, playsinline: 1, rel: 0, origin: location.origin }; state.key = key; state.current = current; if (startSeconds) playerVars.start = startSeconds; state.player = new YT.Player('player', { width: '100%', height: '100%', videoId: current.youtube_id, playerVars, events: { onReady: () => { state.player.mute(); state.soundOn = false; soundLabel(); state.player.playVideo(); restoreSound(); }, onEnded: () => sync(true), onError: () => sync(true), onAutoplayBlocked: () => { state.player.mute(); state.player.playVideo(); } } }); }
async function startInitialPlayback() { if (state.player || state.initialising) return; state.initialising = true; try { const timeline = await startupTimeline; renderTimeline(timeline); if (timeline.current) createInitialPlayer(timeline.current); } catch { state.initialising = false; message('編成を読み込めませんでした。'); } }
window.onYouTubeIframeAPIReady = startInitialPlayback;
if (window.YT?.Player) startInitialPlayback();
$('#sound-toggle').addEventListener('click', () => { state.soundWanted = !state.soundOn; localStorage.setItem('hachijo-tv-sound', state.soundWanted ? 'on' : 'off'); if (!state.player) return; if (state.soundWanted) { state.player.unMute(); state.player.playVideo(); setTimeout(() => { state.soundOn = !state.player.isMuted(); soundLabel(); }, 100); } else { state.player.mute(); state.soundOn = false; soundLabel(); } });
$('#fullscreen-toggle').addEventListener('click', fullscreen); ['fullscreenchange', 'webkitfullscreenchange'].forEach(type => document.addEventListener(type, () => { const active = document.fullscreenElement || document.webkitFullscreenElement; if (!active) unlockOrientation(); fullscreenLabel(Boolean(active)); }));
soundLabel(); recordAccess(); loadHot10();
