const $d = s => document.querySelector(s);
const ids = value => [...new Set((value.match(/(?:v=|youtu\.be\/)([\w-]{11})/g) || []).map(x => x.match(/([\w-]{11})$/)[1]))];
const jstParts = date => Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
const plusDays = (parts, n) => { const d=new Date(Date.UTC(+parts.year,+parts.month-1,+parts.day+n)); return {year:String(d.getUTCFullYear()),month:String(d.getUTCMonth()+1).padStart(2,'0'),day:String(d.getUTCDate()).padStart(2,'0')}; };
const dateText = p => `${p.year}-${p.month}-${p.day}`;
let apiReady;
window.onYouTubeIframeAPIReady = () => apiReady?.();
function verify(videoId) { return new Promise(async resolve => { await new Promise(done => { if (window.YT?.Player) done(); else apiReady = done; }); const host = document.createElement('div'); host.hidden = true; document.body.append(host); let player, done = false; const finish = result => { if (done) return; done = true; try { player?.destroy(); } catch {} host.remove(); resolve(result); }; const timeout = setTimeout(() => finish({ ok: false, error: 'timeout' }), 8000); player = new YT.Player(host, { videoId, playerVars: { controls: 0, playsinline: 1 }, events: { onReady: event => setTimeout(() => { clearTimeout(timeout); const data = event.target.getVideoData(); finish({ ok: true, title: data.title, channel: data.author, duration: Math.round(event.target.getDuration()) }); }, 600), onError: event => { clearTimeout(timeout); finish({ ok: false, error: `YouTube error ${event.data}` }); } } }); }); }
function renderDrafts(){const drafts=JSON.parse(localStorage.getItem('hachijo-tv-drafts')||'[]');$d('#drafts').innerHTML=drafts.length?`<p class="draft-note">この端末の下書き ${drafts.length} 件。公開登録にはGitHubでの認証・commitが必要です。</p>${drafts.map(x=>`<article class="candidate"><div><p class="candidate-kicker">${x.kind} / ${x.ok?'EMBED OK':'CHECK FAILED'}</p><h3>${x.title||x.youtubeId}</h3><p class="candidate-meta">${x.channel||''} · ${Math.floor((x.duration||0)/60)} min</p></div><a href="https://www.youtube.com/watch?v=${x.youtubeId}" target="_blank" rel="noreferrer">YOUTUBE</a></article>`).join('')}`:'<p class="candidate-empty">下書きはありません。</p>';}
async function start(){const [library,programming]=await Promise.all(['library.json','programming.json'].map(x=>fetch(x,{cache:'no-store'}).then(r=>r.json())));HachijoScheduler.configure(library,programming);const base=jstParts(new Date());$d('#week').innerHTML=Array.from({length:7},(_,n)=>{const day=plusDays(base,n),items=HachijoScheduler.buildSchedule(day);return `<details ${n===0?'open':''}><summary>${dateText(day)}</summary>${items.map(x=>`<p><time>${HachijoScheduler.formatTime(x.start)}</time><span>${x.programLabel}</span><small>${x.sourceTitle||x.sourceChannel||''}</small></p>`).join('')}</details>`}).join('');renderDrafts();$d('#check').addEventListener('click',async()=>{const videoIds=ids($d('#urls').value),kind=$d('#kind').value;if(!videoIds.length)return;$d('#check').disabled=true;const drafts=JSON.parse(localStorage.getItem('hachijo-tv-drafts')||'[]');for(const youtubeId of videoIds){const result=await verify(youtubeId);drafts.push({youtubeId,kind,...result});}localStorage.setItem('hachijo-tv-drafts',JSON.stringify(drafts));$d('#check').disabled=false;renderDrafts();});}
start();
