const $d=s=>document.querySelector(s),sb=window.supabase.createClient(window.FM_HACHIJO_SUPABASE.url,window.FM_HACHIJO_SUPABASE.publishableKey);
let items=[],libraryByYoutube=new Map(),pending=null,ytPromise,activeFamily='all',activeRights='all',editingId=null,hotCharts=[];
const familyLabel={music:'MUSIC',hachijo_taiko:'HACHIJO TAIKO',power_push:'POWER PLAY',sports:'SPORTS',hachijo_picks:'HACHIJO PICKS',island_view:'ISLAND VIEW',tokyo_relay:'TOKYO RELAY'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const idFrom=v=>(v.match(/(?:youtu\.be\/|[?&]v=|\/embed\/)([\w-]{11})/)||[])[1];
const dur=n=>{n=Number(n)||0;return `${Math.floor(n/3600)?`${Math.floor(n/3600)}h `:''}${Math.floor(n%3600/60)}m`};
const sourceUrl=x=>x?.source_url||x?.youtube_url||x?.youtube_id?`https://www.youtube.com/watch?v=${x.youtube_id}`:'';
const external=(url,label)=>url?`<a class="source-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`:esc(label);
const rightsValue=x=>x.rights_cleared===true?'true':x.rights_cleared===false?'false':'';
const rightsMark=x=>x.rights_cleared===true?'✓':x.rights_cleared===false?'—':'?';
const jstParts=(value=new Date())=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(x=>[x.type,x.value]));
const jstKey=value=>{const p=jstParts(value);return `${p.year}-${p.month}-${p.day}`};
const jstDate=value=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short'}).format(new Date(value));
const jstTime=value=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));
const hot10Date=()=>{const p=jstParts();const utc=Date.UTC(+p.year,+p.month-1,+p.day)-(Number(p.hour)<3?86400000:0);return new Date(utc).toISOString().slice(0,10)};
function setView(view){document.querySelectorAll('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==view);document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.view===view)));history.replaceState(null,'',`#${view}`)}
function renderSummary(){const families=[...new Set(items.map(x=>x.family_code))];$d('#summary').innerHTML=families.map(f=>`<p><span>${esc(familyLabel[f]||f)}</span><strong>${items.filter(x=>x.family_code===f).length}</strong></p>`).join('')||'<p>素材はありません。</p>'}
function renderFilters(){const families=['all',...new Set(items.map(x=>x.family_code))];$d('#family-filters').innerHTML=families.map(f=>`<button type="button" data-family="${esc(f)}" class="${activeFamily===f?'is-active':''}">${f==='all'?'ALL':esc(familyLabel[f]||f)}</button>`).join('');$d('#rights-filters').innerHTML=[['all','ALL'],['true','✓'],['false','—'],['unset','?']].map(([v,label])=>`<button type="button" data-rights="${v}" class="${activeRights===v?'is-active':''}">${label}</button>`).join('')}
function renderLibrary(){const query=$d('#search').value.trim().toLowerCase(),sort=$d('#sort').value;let rows=items.filter(x=>`${x.family_code} ${x.title} ${x.channel_name||''} ${x.youtube_id}`.toLowerCase().includes(query)).filter(x=>activeFamily==='all'||x.family_code===activeFamily).filter(x=>activeRights==='all'||(activeRights==='unset'?x.rights_cleared==null:String(x.rights_cleared)===activeRights));rows.sort((a,b)=>sort==='duration-desc'?b.duration_secs-a.duration_secs:sort==='duration-asc'?a.duration_secs-b.duration_secs:sort==='title-desc'?String(b.title).localeCompare(String(a.title),'ja'):String(a.title).localeCompare(String(b.title),'ja'));$d('#library').innerHTML=rows.map(x=>`<article class="library-row" data-id="${x.id}"><p class="candidate-kicker">${esc(familyLabel[x.family_code]||x.family_code)}</p><div class="library-main"><div><h3>${external(sourceUrl(x),esc(x.title))}</h3><p class="candidate-meta">${esc(x.channel_name||'—')} · ${dur(x.duration_secs)}</p></div><p class="rights-mark" title="RIGHTS ${rightsMark(x)}">RIGHTS ${rightsMark(x)}</p><div class="dashboard-actions"><button type="button" data-a="edit">EDIT</button><button type="button" data-a="delete" class="danger-button">DELETE</button></div></div></article>`).join('')||'<p class="empty-state">該当する素材はありません。</p>';renderFilters()}
function renderTimetable(rows){const byDay=rows.reduce((out,row)=>{const day=jstKey(row.start_at);(out[day]??=[]).push(row);return out},{});$d('#week').innerHTML=Object.entries(byDay).slice(0,3).map(([day,entries,index])=>`<details${index===0?' open':''}><summary>${esc(jstDate(`${day}T12:00:00+09:00`))}${index===0?' TODAY':''}</summary>${entries.map(row=>{const item=libraryByYoutube.get(row.youtube_id),label=esc(row.title||item?.title||'—'),link=item?external(sourceUrl(item),label):label;return `<div class="schedule-row"><time>${jstTime(row.start_at)}–${jstTime(row.end_at)}</time><strong>${esc(familyLabel[row.family_code]||row.family_code)}</strong><span>${link}</span></div>`}).join('')}</details>`).join('')||'<p>現在、確定済みの編成はありません。</p>'}
async function timetable(){const now=new Date().toISOString(),until=new Date(Date.now()+72*3600000).toISOString(),{data,error}=await sb.from('schedule_items').select('family_code,youtube_id,title,start_at,end_at').gte('end_at',now).lt('start_at',until).order('start_at');if(error){$d('#week').textContent='タイムテーブルを読み込めませんでした。';return}$d('#today-label').textContent=jstDate(now);$d('#today-status').textContent='3日分のタイムテーブルを確認できます。';renderTimetable(data||[])}
async function library(){const {data,error}=await sb.from('content_items').select('*').order('duration_secs',{ascending:false});if(error){$d('#add-status').textContent=error.message;return}items=data||[];libraryByYoutube=new Map(items.map(x=>[x.youtube_id,x]));renderSummary();renderLibrary()}
function renderOnAir(row){const item=row&&libraryByYoutube.get(row.youtube_id),title=row?.title||item?.title||'現在の編成を準備中';$d('#on-air').innerHTML=row?`<p class="candidate-kicker">${esc(familyLabel[row.family_code]||row.family_code)}</p><h2>${item?external(sourceUrl(item),esc(title)):esc(title)}</h2>`:'現在の編成を準備中'}
async function onAir(){const now=new Date().toISOString(),{data}=await sb.from('schedule_items').select('family_code,youtube_id,title,end_at').lte('start_at',now).gt('end_at',now).limit(1).maybeSingle();renderOnAir(data)}
function loadYT(){if(window.YT?.Player)return Promise.resolve(window.YT);if(ytPromise)return ytPromise;ytPromise=new Promise((resolve,reject)=>{window.onYouTubeIframeAPIReady=()=>resolve(window.YT);const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=reject;document.head.append(s)});return ytPromise}
async function duration(id){const YT=await loadYT(),node=document.createElement('div');node.id=`p-${id}-${Date.now()}`;node.style.cssText='position:fixed;left:-1px;bottom:-1px;width:1px;height:1px;opacity:0';document.body.append(node);return new Promise(resolve=>{let player,timer,done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);try{player?.destroy()}catch{}node.remove();resolve(value)};timer=setTimeout(()=>finish(null),12000);try{player=new YT.Player(node.id,{videoId:id,width:'1',height:'1',playerVars:{controls:0,playsinline:1},events:{onReady:e=>{const read=()=>{const value=Math.round(e.target.getDuration());if(value>0)finish(value)};read();setTimeout(read,1000);setTimeout(read,2500)},onError:()=>finish(null)}})}catch{finish(null)}})}
async function add(){if(pending){const missing=pending.filter(x=>!x.duration_secs);for(const x of missing)x.duration_secs=+$d(`[data-d="${x.youtube_id}"]`)?.value;if(missing.some(x=>!x.duration_secs))return $d('#add-status').textContent='取得できない動画だけ秒数を入力してください。';const {error}=await sb.from('content_items').upsert(pending,{onConflict:'youtube_id'});if(error)return $d('#add-status').textContent=error.message;$d('#add-status').textContent=`${pending.length}件を保存しました。`;pending=null;$d('#urls').value='';$d('#duration-fallbacks').hidden=true;return library()}const urls=$d('#urls').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),parsed=urls.map(url=>({url,id:idFrom(url)}));if(!parsed.length||parsed.some(x=>!x.id))return $d('#add-status').textContent='YouTube URLを1行に1本入力してください。';const rows=[];for(const [index,x] of parsed.entries()){$d('#add-status').textContent=`確認中 ${index+1}/${parsed.length}`;let meta={};try{const response=await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(x.url)}&format=json`);meta=await response.json()}catch{}rows.push({family_code:$d('#family').value,youtube_id:x.id,title:meta.title||x.id,channel_name:meta.author_name||null,duration_secs:await duration(x.id).catch(()=>null),rights_cleared:$d('#add-rights').value===''?null:$d('#add-rights').value==='true'})}pending=rows;const missing=rows.filter(x=>!x.duration_secs);if(missing.length){$d('#duration-fallbacks').hidden=false;$d('#duration-fallbacks').innerHTML=missing.map(x=>`<label>${esc(x.title)}<input type="number" min="1" data-d="${x.youtube_id}" placeholder="seconds"></label>`).join('');$d('#add-status').textContent='取得できない動画があります。秒数を入力して再度SAVEしてください。';return}add()}
function startEdit(item){editingId=item.id;$d('#edit-panel').hidden=false;$d('#edit-family').innerHTML=Object.entries(familyLabel).filter(([key])=>!['island_view','tokyo_relay'].includes(key)).map(([key,label])=>`<option value="${key}">${label}</option>`).join('');$d('#edit-family').value=item.family_code;$d('#edit-title').value=item.title;$d('#edit-rights').value=rightsValue(item);$d('#edit-panel').scrollIntoView({behavior:'smooth',block:'nearest'})}
async function saveEdit(){const item=items.find(x=>x.id===editingId);if(!item)return;const value=$d('#edit-rights').value,{error}=await sb.from('content_items').update({family_code:$d('#edit-family').value,title:$d('#edit-title').value.trim()||item.title,rights_cleared:value===''?null:value==='true'}).eq('id',item.id);if(error)return alert(error.message);editingId=null;$d('#edit-panel').hidden=true;library()}
function exportCsv(){const rows=items.filter(x=>/youtube\.com|youtu\.be/i.test(sourceUrl(x))).map(x=>({library_id:x.id,family:familyLabel[x.family_code]||x.family_code,title:x.title,channel:x.channel_name||'',duration_seconds:x.duration_secs,youtube_id:x.youtube_id,youtube_url:sourceUrl(x),rights_cleared:x.rights_cleared===true?'TRUE':x.rights_cleared===false?'FALSE':''})),fields=['library_id','family','title','channel','duration_seconds','youtube_id','youtube_url','rights_cleared'],quote=v=>`"${String(v??'').replaceAll('"','""')}"`,csv=`\ufeff${fields.join(',')}\r\n${rows.map(row=>fields.map(key=>quote(row[key])).join(',')).join('\r\n')}\r\n`,url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`fm-hachijo-youtube-check-${jstKey()}.csv`;link.click();URL.revokeObjectURL(url)}
function movementClass(value){return value==='NEW'||value==='RE'?'is-gold':String(value||'').startsWith('↑')?'is-up':String(value||'').startsWith('↓')?'is-down':''}
function renderHot10(date){const chart=hotCharts.find(x=>x.date===date)||hotCharts[0];if(!chart){$d('#hot10-days').textContent='利用可能な履歴はありません。';$d('#hot10-list').replaceChildren();return}$d('#hot10-days').innerHTML=hotCharts.map(x=>`<button type="button" data-hot-date="${x.date}" class="${x.date===chart.date?'is-active':''}">${x.date.slice(5).replace('-','.')}</button>`).join('');$d('#hot10-list').innerHTML=chart.chart.map(x=>`<div class="hot10-admin-row"><b>${String(x.rank).padStart(2,'0')}</b><div><strong>${esc(x.title)}</strong><span>${esc(x.artist)}</span></div><em class="${movementClass(x.movement)}">${esc(x.movement)}</em></div>`).join('')}
async function loadHot10(){const start=new Date(`${hot10Date()}T00:00:00Z`),dates=Array.from({length:7},(_,i)=>new Date(start.getTime()-i*86400000).toISOString().slice(0,10));const results=await Promise.all(dates.map(async day=>{try{const response=await fetch(`hachijo_hot10/hot10_output/${day}.json`,{cache:'no-store'});if(!response.ok)return null;const json=await response.json();return Array.isArray(json.chart)&&json.chart.length===10?json:null}catch{return null}}));hotCharts=results.filter(Boolean);if(!hotCharts.length){try{const response=await fetch('hachijo_hot10/hot10_output/latest.json',{cache:'no-store'}),json=await response.json();if(Array.isArray(json.chart))hotCharts=[json]}catch{}}renderHot10(hotCharts[0]?.date);$d('#hot10-preview').innerHTML=hotCharts[0]?.chart.slice(0,3).map(x=>`<p><b>${String(x.rank).padStart(2,'0')}</b> ${esc(x.title)}</p>`).join('')||'利用可能な履歴はありません。'}
async function admin(){const {data:{session}}=await sb.auth.getSession();if(!session)return;const {data:profile}=await sb.from('profiles').select('is_admin').single();if(!profile?.is_admin){$d('#auth-status').textContent='管理者権限がありません。';return}$d('#login').hidden=true;$d('#admin').hidden=false;$d('#admin-email').hidden=false;$d('#logout').hidden=false;$d('#admin-email').textContent=session.user.email;await library();await Promise.all([timetable(),onAir(),loadHot10()]);setView(location.hash.slice(1)||'overview')}
async function login(){const button=$d('#login-button'),status=$d('#auth-status'),email=$d('#email').value.trim(),password=$d('#password').value;if(!email||!password){status.textContent='Email と Password を入力してください。';return}button.disabled=true;status.textContent='ログイン中…';try{const {error}=await sb.auth.signInWithPassword({email,password});if(error){status.textContent=error.message;return}await admin()}catch(error){status.textContent=`ログインできませんでした: ${error.message||'通信エラー'}`}finally{button.disabled=false}}
$d('#login-button').onclick=login;$d('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$d('.dashboard-tabs').onclick=e=>{const button=e.target.closest('[data-view]');if(button)setView(button.dataset.view)};document.querySelectorAll('.view-jump').forEach(x=>x.onclick=()=>setView(x.dataset.jump));$d('#regenerate').onclick=async()=>{if(!confirm('現在時刻以降の72時間を置き換えます。'))return;$d('#regen-status').textContent='生成中…';const {error}=await sb.rpc('regenerate_schedule');$d('#regen-status').textContent=error?.message||'72時間分を再生成しました。';await timetable();await onAir()};$d('#add-toggle').onclick=()=>{$d('#add-form').hidden=!$d('#add-form').hidden};$d('#add').onclick=add;$d('#urls').oninput=()=>{pending=null;$d('#duration-fallbacks').hidden=true};$d('#search').oninput=renderLibrary;$d('#sort').onchange=renderLibrary;$d('#family-filters').onclick=e=>{const button=e.target.closest('[data-family]');if(button){activeFamily=button.dataset.family;renderLibrary()}};$d('#rights-filters').onclick=e=>{const button=e.target.closest('[data-rights]');if(button){activeRights=button.dataset.rights;renderLibrary()}};$d('#export-csv').onclick=exportCsv;$d('#edit-cancel').onclick=()=>{$d('#edit-panel').hidden=true;editingId=null};$d('#edit-save').onclick=saveEdit;$d('#library').onclick=async e=>{const button=e.target.closest('button'),item=button&&items.find(x=>x.id===button.closest('[data-id]')?.dataset.id);if(!item)return;if(button.dataset.a==='delete'){if(confirm(`「${item.title}」を削除します。`)){const {error}=await sb.from('content_items').delete().eq('id',item.id);if(error)alert(error.message);else library()}}else if(button.dataset.a==='edit')startEdit(item)};$d('#hot10-days').onclick=e=>{const button=e.target.closest('[data-hot-date]');if(button)renderHot10(button.dataset.hotDate)};admin();
