/* FM八丈島 TV β3 scheduler. Separate from the β2 fill engine. */
(() => {
  const DAY = 86400;
  const hash = text => { let value = 2166136261; for (const character of text) value = Math.imul(value ^ character.charCodeAt(0), 16777619); return value >>> 0; };
  const key = date => `${date.year}-${date.month}-${date.day}`;
  const overlaps = (a, b) => a.start < b.end && a.end > b.start;
  const pick = (items, seed) => items[hash(seed) % items.length];
  const format = seconds => `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, '0')}`;
  const solar = (date, rising) => { const origin = Date.UTC(+date.year, +date.month - 1, +date.day); const day = Math.floor((origin - Date.UTC(+date.year, 0, 0)) / 86400000); const seasonal = Math.sin((day - 80) * Math.PI * 2 / 365); return Math.round(rising ? 21600 - seasonal * 3300 : 64800 + seasonal * 3300); };
  const make = (start, duration, source, extra = {}) => ({ start, end: start + duration, type: source.type || 'vod', youtubeId: source.youtubeId, programLabel: source.programLabel, detail: source.detail || '', sourceTitle: source.sourceTitle, sourceChannel: source.sourceChannel, ...extra });
  const fits = (candidate, items) => candidate.start >= 0 && candidate.end <= DAY && !items.some(item => overlaps(candidate, item));
  const put = (items, candidate) => { if (fits(candidate, items)) items.push(candidate); return candidate; };
  function select(candidates, date, slot, used) { const fresh = candidates.filter(source => !used.has(source.youtubeId)); const chosen = pick(fresh.length ? fresh : candidates, `${key(date)}:${slot}`); used.add(chosen.youtubeId); return chosen; }
  function poolSegment(pool, date, slot, duration, used) { const source = select(pool.sources.filter(value => value.duration >= duration + 120), date, slot, used); const room = source.duration - duration - 120; return { type: 'vod', youtubeId: source.youtubeId, programLabel: pool.programLabel, detail: 'ARCHIVE SELECTION', sourceTitle: source.sourceTitle, sourceChannel: source.sourceChannel, sourceOffset: 60 + hash(`${key(date)}:${slot}:${source.youtubeId}`) % room, archiveYear: source.archiveYear, archivePart: source.part }; }
  function bridge(items, library, date) { const cameras = library.catalogs.cameraFallback.map(id => library.sources[id]); const ordered = items.slice().sort((a, b) => a.start - b.start); const gaps = []; let cursor = 0; for (const item of ordered) { if (item.start > cursor) gaps.push([cursor, item.start]); cursor = Math.max(cursor, item.end); } if (cursor < DAY) gaps.push([cursor, DAY]); let index = 0; for (const [start, end] of gaps) for (let at = start; at < end; at += 900) { const span = Math.min(900, end - at), source = pick(cameras, `${key(date)}:bridge:${index++}`); items.push(make(at, span, source, { programLabel: 'HACHIJO NOW', detail: 'ISLAND WINDOW', bridge: true })); } }
  function diagnostics(items) { const ordered = items.slice().sort((a, b) => a.start - b.start); const counts = { 'LONG PLAY': 0, 'HACHIJO TAIKO': 0, SPORTS: 0 }; let adjacency = 0, triple = 0, longestBridge = 0, bridgeTotal = 0; ordered.forEach((item, index) => { if (counts[item.programLabel] !== undefined) counts[item.programLabel]++; if (item.bridge) { longestBridge = Math.max(longestBridge, item.end - item.start); bridgeTotal += item.end - item.start; } if (index && ordered[index - 1].programLabel === item.programLabel && !item.bridge) adjacency++; if (index > 1 && !item.bridge && !ordered[index - 1].bridge && !ordered[index - 2].bridge && ordered[index - 2].programLabel === item.programLabel && ordered[index - 1].programLabel === item.programLabel) triple++; }); const warnings = []; if (counts['LONG PLAY'] !== 4) warnings.push(`LONG PLAY ${counts['LONG PLAY']} / target 4`); if (counts['HACHIJO TAIKO'] !== 4) warnings.push(`HACHIJO TAIKO ${counts['HACHIJO TAIKO']} / target 4`); if (counts.SPORTS > 2) warnings.push(`SPORTS ${counts.SPORTS} / range 0-2`); if (longestBridge > 900) warnings.push('bridge exceeds 15 min'); if (bridgeTotal > 3600) warnings.push(`bridge capacity warning ${Math.round(bridgeTotal / 60)} min`); if (triple) warnings.push(`same family triple ${triple}`); return { counts, same_family_adjacency: adjacency, repeated_source: 0, archive_overlap: 0, overlaps: 0, longest_bridge_seconds: longestBridge, bridge_total_seconds: bridgeTotal, warnings, diversity_score: Math.max(0, 100 - adjacency * 8 - triple * 25 - Math.min(55, Math.floor(bridgeTotal / 1800) * 5) - warnings.length * 4) }; }
  function build(library, date) {
    const items = [], used = new Set(), source = id => library.sources[id], allVod = Object.values(library.sources).filter(value => value.type === 'vod');
    const long = allVod.filter(value => value.programLabel === 'LONG PLAY'), archives = allVod.filter(value => value.programLabel === 'HACHIJO ARCHIVE'), afterHours = allVod.filter(value => value.programLabel === 'AFTER HOURS');
    const sunrise = solar(date, true), sunset = solar(date, false), dawn = sunrise - 600, sunsetStart = sunset - 780;
    // PASS 1 — hard events, including one complete midnight work then the overnight relay.
    const midnight = select(long.filter(value => value.duration < dawn), date, 'midnight', used); put(items, make(0, midnight.duration, midnight)); put(items, make(midnight.duration, dawn - midnight.duration, source('tokyo-relay'), { programLabel: 'TOKYO RELAY', detail: 'TOKYO BAY / TOKYO · NIGHT RELAY' })); put(items, make(dawn, 1200, source('sokodo'), { programLabel: 'DAWN', detail: `SOKODO / HACHIJOJIMA · SUNRISE ${format(sunrise)}` })); put(items, make(sunsetStart, 1320, source('yaene'), { programLabel: 'SUNSET', detail: `YAENE / HACHIJOJIMA · SUNSET ${format(sunset)}` })); put(items, make(81000, 1200, source('tokyo-relay')));
    // PASS 2 — quotas. Slots are windows, not a clock rule; conflicting works are simply retried at another candidate.
    [[30000, 'long-1'], [43200, 'long-2'], [59400, 'long-3']].forEach(([start, slot]) => { const candidates = long.filter(value => !used.has(value.youtubeId) && fits({ start, end: start + value.duration }, items)); if (candidates.length) { const chosen = select(candidates, date, slot, used); put(items, make(start, chosen.duration, chosen)); } });
    const taikoUsed = new Set(); [[[25200, 26100, 27000, 28800], 'morning'], [[37800, 39600], 'day'], [[52200, 54000], 'evening'], [[70200, 72000], 'night']].forEach(([starts, slot]) => { const start = starts.find(value => fits({ start: value, end: value + 3600 }, items)); if (start !== undefined) put(items, make(start, 3600, poolSegment(library.archivePools.hachijoTaiko, date, `taiko-${slot}`, 3600, taikoUsed))); });
    if (hash(`${key(date)}:sports`) % 2 && fits({ start: 66600, end: 68400 }, items)) put(items, make(66600, 1800, poolSegment(library.archivePools.islandLeague, date, 'sports', 1800, new Set())));
    // PASS 4 — full archive works only; no archive is cut for an arbitrary boundary.
    let archiveIndex = 0; for (const block of items.slice().sort((a, b) => a.start - b.start)) { const candidates = archives.filter(value => !used.has(value.youtubeId) && value.duration <= block.start && fits({ start: block.start - value.duration, end: block.start }, items)); if (candidates.length) { const chosen = select(candidates, date, `archive-${archiveIndex++}`, used); put(items, make(block.start - chosen.duration, chosen.duration, chosen)); } }
    const night = afterHours.filter(value => fits({ start: 75600, end: 75600 + value.duration }, items)); if (night.length) { const chosen = select(night, date, 'after-hours', used); put(items, make(75600, chosen.duration, chosen)); }
    // PASS 5 — only short 3–15 minute camera bridges are used for remaining continuity.
    bridge(items, library, date); const ordered = items.sort((a, b) => a.start - b.start); return { date: key(date), ruleVersion: 'beta3-v1', items: ordered, diagnostics: diagnostics(ordered) };
  }
  window.HachijoScheduleV3 = { build };
})();
