create table if not exists public.profiles (id uuid primary key references auth.users on delete cascade, is_admin boolean not null default false, created_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id) values (new.id) on conflict do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table if not exists public.program_families (code text primary key, display_name text not null, subtitle text, schedule_role text not null, daily_min integer not null default 0, daily_max integer not null default 0, preferred_windows jsonb not null default '[]', min_duration integer, max_duration integer, bridge_max_minutes integer, enabled boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.content_items (id uuid primary key default gen_random_uuid(), family_code text not null references public.program_families(code), youtube_id text not null unique, source_url text not null, source_title text not null, source_channel text, public_title text, duration_seconds integer not null check(duration_seconds > 0), content_type text not null default 'vod', atomic boolean not null default true, enabled boolean not null default true, verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.archive_sources (id uuid primary key default gen_random_uuid(), pool_code text not null, youtube_id text not null unique, source_url text not null, source_title text not null, source_channel text, archive_year integer, part text, duration_seconds integer not null check(duration_seconds > 0), verified boolean not null default false, enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.daily_schedules (id uuid primary key default gen_random_uuid(), broadcast_date date not null unique, rule_version text not null, diversity_score numeric, diagnostics jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.schedule_items (id uuid primary key default gen_random_uuid(), schedule_id uuid not null references public.daily_schedules(id) on delete cascade, start_at timestamptz not null, end_at timestamptz not null, family_code text not null references public.program_families(code), content_id uuid references public.content_items(id), source_id uuid references public.archive_sources(id), start_offset integer not null default 0, end_offset integer, detail jsonb not null default '{}', check(end_at > start_at));
create table if not exists public.playout_history (id uuid primary key default gen_random_uuid(), broadcast_date date not null, start_at timestamptz not null, end_at timestamptz not null, family_code text not null, content_id uuid, source_id uuid, artist text, source_channel text, start_offset integer, end_offset integer, schedule_id uuid references public.daily_schedules(id), created_at timestamptz not null default now());
alter table public.program_families enable row level security; alter table public.content_items enable row level security; alter table public.archive_sources enable row level security; alter table public.daily_schedules enable row level security; alter table public.schedule_items enable row level security; alter table public.playout_history enable row level security; alter table public.profiles enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_admin) $$;
create policy "public read enabled families" on public.program_families for select using (enabled or public.is_admin());
create policy "public read enabled content" on public.content_items for select using (enabled or public.is_admin());
create policy "public read enabled archives" on public.archive_sources for select using (enabled or public.is_admin());
create policy "public read schedules" on public.daily_schedules for select using (true);
create policy "public read schedule items" on public.schedule_items for select using (true);
create policy "admin all families" on public.program_families for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all content" on public.content_items for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all archives" on public.archive_sources for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all schedules" on public.daily_schedules for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all schedule items" on public.schedule_items for all using (public.is_admin()) with check (public.is_admin());
create policy "admin read history" on public.playout_history for select using (public.is_admin());
create policy "admin write history" on public.playout_history for insert with check (public.is_admin());
create policy "profile self read" on public.profiles for select using (id=auth.uid());

-- Data API privileges are deliberately narrower than the RLS policies above.
grant usage on schema public to anon, authenticated;
revoke all on table public.program_families, public.content_items, public.archive_sources, public.daily_schedules, public.schedule_items, public.playout_history, public.profiles from anon, authenticated;
grant select on table public.program_families, public.content_items, public.archive_sources, public.daily_schedules, public.schedule_items to anon;
grant select, insert, update, delete on table public.program_families, public.content_items, public.archive_sources, public.daily_schedules, public.schedule_items to authenticated;
grant select, insert on table public.playout_history to authenticated;
grant select on table public.profiles to authenticated;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
